spring:
  banner:
    location: classpath:/Banner.txt
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    user:
      name: username
      password: password

app:
  name: "sample-rest-api"
  contact: opinilla@gmail.com
  git: https://github.com/Solksjaer/sample-rest-api.git
  currency:
    bitcoin: 1.2
    dogecoin: 3.3