spring:
  banner:
    location: classpath:/Banner.txt
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    user:
      name: username
      password: password

app:
  name: "sample-rest-api"
  contact: opinilla@gmail.com
  git: https://github.com/Solksjaer/sample-rest-api.git
  currency:
    bitcoin: 1.2,2.3,3.4,4.5,5.6
    dogecoin: 3.3,4.4,5.5,6.6,7.7